### ISSUE TITLE
Historias de usuario

### ISSUE THREAD

**Issue by cfgonzalezb94** [ISWPOLI/Servicios_Bibliotecarios#1]
**Crear historias de usuario**
Después de el levantamiento de requerimientos se crean historias de usuarios.
**Descripción de la tarea**
- [x] Definir servicios bibliotecarios
- [x] Definir tipo de juego
- [ ] Definir personajes de juego
- [ ] Definir escenarios de juego

**Comment by Lakes1234** [comment]
Pepito es un estudiante de primer semestre.

**Comment by Lakes1234** [comment]
Préstamo de libros
Yo como usuario requiero un préstamo de libro, el bibliotecario me da varias opciones, debo consultarlo si existe, lo cual lo puedo hacerlo a través de el o consultando en el aplicativo de la biblioteca en cual esta en linea o existe computadores dentro de la biblioteca para realizar esta consulta.
Encontré el libro y me dice que hay disponibilidad de acuerdo a lo siguiente:
Existen libros con etiquetas de colores que traduce lo siguiente:

Libros de reserva
Descripción 1: 
Libro de préstamo
Descripción 2:
Libro virtual
Descripción 3:

**Comment by amauric30** [comment]
hola compañeros no puedo subir ningun documento, el upload no est disponible para cuenta

**Comment by amelissagomez** [comment]
Hola @amauric30  para subir documento realizar el paso a paso de issue #26 .

**Comment by amauric30** [comment]
ya se subió la nueva historia de usuario que propongo, en un comentario más adelante
