### ISSUE TITLE
Especificación Nivel 5 Adquisición de Materiales

### ISSUE THREAD

**Issue by amelissagomez** [ISWPOLI/Servicios_Bibliotecarios#10]
**Especificación Nivel 5 Adquisición de Materiales**
Especificación Nivel 5 Adquisición de Materiales
**Tareas**

- [ ] Especificación Personajes del juego en el nivel
- [ ] Herramientas del juego en el nivel
- [ ] Especificación historia nivel 5 (Adquisición de Materiales)

**Comment by amauric30** [comment]
5. Pepito tienes que tener en cuenta algo muy importante que corresponde a nuestra seguridad al salir de biblioteca:
5.1. Cuantas hayas pedido cualquier material de la biblioteca solo podrás salir con este material una vez sea registrado por el bibliotecario de turno, es decir siempre tienes que venir a esta posición para que yo registre el código de cada material y puedas salir si lo registro como préstamo a domicilio.
