### ISSUE TITLE
Ver Película en la Biblioteca Nivel 2

### ISSUE THREAD

**Issue by amelissagomez** [ISWPOLI/Servicios_Bibliotecarios#15]
**Ver Película en la Biblioteca**
Especificación de momento de la historia, como el personaje interactua y llega al lugar donde se encuentra el bibliotecario para realizar tramite para separar película y un cubículo.
**Tareas**
- [ ] Mockup Escena con Bibliotecario
- [ ] Mockup Escena en Cubículo
- [ ] Definición de roles
- [ ] Crear dialogos de personajes

**Comment by amauric30** [comment]
4. Mira Pepito aquí puedes también mirar algunos filmes de películas en las salas de video, estas salas cuentan con los siguientes elementos:
4.1. Un televisor, el cual debes de cuidar.
4.2. Un reproductor de cds al cual también debes de cuidar.
4.3. La sala cuenta con 4 puestos, el cual puedes entrar con más compañeros de estudio.
4.4. Puedes pedirla para verla en estas salas o puedes pedirla a domicilio.
