### ISSUE TITLE
Libro en Otra Universidad Nivel 4

### ISSUE THREAD

**Issue by amelissagomez** [ISWPOLI/Servicios_Bibliotecarios#18]
**Libro en otra universidad**
Especificar escena del juego, como el personaje interactua y llega al lugar donde se encuentra el bibliotecario para diligenciar el formato de libro en otra universidad
**Tareas**
- [ ] Mockup Escena
- [ ] Definición de roles
- [ ] Crear diálogos de personajes

**Comment by amauric30** [comment]
2.4. préstamo de libros virtuales (ínter-bibliotecario)
Para este servicio tienes yo por sistema sisnab de la biblioteca, la biblioteca esta conectada a varias bibliotecas ya sean universidades o bibliotecas públicas. Yo puedo hacer la solicitud de un libro que necesites de esas bibliotecas externas y tu tendrás que ir a retirar el libro que pedimos aquí.
