### ISSUE TITLE
Consulta de libros por Internet Nivel 6

### ISSUE THREAD

**Issue by amelissagomez** [ISWPOLI/Servicios_Bibliotecarios#21]
**Consulta de libros por Internet**
Consulta de libros por Internet 
**Tareas**

**Comment by amauric30** [comment]
2.4. préstamo de libros virtuales (ínter-bibliotecario)
Para este servicio tienes yo por sistema sisnab de la biblioteca, la biblioteca esta conectada a varias bibliotecas ya sean universidades o bibliotecas públicas. Yo puedo hacer la solicitud de un libro que necesites de esas bibliotecas externas y tu tendrás que ir a retirar el libro que pedimos aquí.
