### ISSUE TITLE
Crear primera parte nivel 1 

### ISSUE THREAD

**Issue by amelissagomez** [ISWPOLI/Servicios_Bibliotecarios#24]
**Crear primera parte nivel 1 **
**Tareas**

**Comment by Lakes1234** [comment]
HU
Préstamo Libros
Evento 1: El estudiante realiza la búsqueda en los computadores especiales
Evento 2: Realiza la búsqueda del libro de acuerdo al código ISBN arrojado por la plataforma
Evento 3: El estudiante identifica el libro y se procede a entregarlo al personal administrativo de la biblioteca 
Evento 4: El administrador solicita el carnet para realizar el proceso de préstamo del libro
Evento 5: Se fija la fecha del préstamo del libro.

**Comment by amauric30** [comment]
2. Pepito, puedes sacar en préstamo libros físicos, pero hay libros de prestamos reservados a algunas horas y no los puedes sacar de la biblioteca:
2.2. préstamo de libros general (domicilio)
2.2.1. etiqueta color
2.3. préstamo de libros con reserva (no domicilio)
2.3.1.etiqueta color
2.4. préstamo de libros virtuales (ínter-bibliotecario)
Para este servicio tienes yo por sistema sisnab de la biblioteca, la biblioteca esta conectada a varias bibliotecas ya sean universidades o bibliotecas públicas. Yo puedo hacer la solicitud de un libro que necesites de esas bibliotecas externas y tu tendrás que ir a retirar el libro que pedimos aquí.
