### ISSUE TITLE
Instalación github y creación de Branch 

### ISSUE THREAD

**Issue by amelissagomez** [ISWPOLI/Servicios_Bibliotecarios#26]
**Instalación github y creación de Branch**
Cada miembro del equipo debe  instalar github y crear su rama.
**Tareas**

- [ ] Instalar Github en el pc (Ingresar al proyecto "Servicios_Bibliotecarios" y en el botón "clone or download"  hacer clic en "Open in desktop")
- [ ] Descargar Proyecto (Volver  a realizar el paso anterior, ingresar al proyecto "Servicios_Bibliotecarios" y en el botón "clone or down"  hacer clic en "Open in desktop")
- [ ] Crear Branch (En la aplicación de escritorio de github, en la parte izquierda, arriba hay un icono en forma de "v" hacer clic en el y crear con su nombre el nuevo branch)

**Comment by amauric30** [comment]
ya esta la tarea realiza, ya adicione mi branch e instalé rpg maker.

**Comment by Lakes1234** [comment]
- [x]  Instalar Github en el pc (Ingresar al proyecto "Servicios_Bibliotecarios" y en el botón "clone or download" hacer clic en "Open in desktop")
 
- [x] Descargar Proyecto (Volver a realizar el paso anterior, ingresar al proyecto "Servicios_Bibliotecarios" y en el botón "clone or down" hacer clic en "Open in desktop")

- [x] Crear Branch (En la aplicación de escritorio de github, en la parte izquierda, arriba hay un icono en forma de "v" hacer clic en el y crear con su nombre el nuevo branch)
![branch](https://cloud.githubusercontent.com/assets/25758873/23842037/b0cf45e8-077f-11e7-990b-7d362b363ccc.png)
