### ISSUE TITLE
Crear historia del juego

### ISSUE THREAD

**Issue by amelissagomez** [ISWPOLI/Servicios_Bibliotecarios#3]
**Crear historia del juego**
Crear historia del juego
**Tareas**
- [ ] Personajes
- [x] Niveles
- [x] Servicios

**Comment by amelissagomez** [comment]
[Historiadepepito.docx](https://github.com/ISWPOLI/Servicios_Bibliotecarios/files/804648/Historiadepepito.docx)

**Comment by amauric30** [comment]
se ha trabajado en la historia del juego, en una tarea mas adelante subi la historia de usuario
