### ISSUE TITLE
Configuración RPG MAKER

### ISSUE THREAD

**Issue by amelissagomez** [ISWPOLI/Servicios_Bibliotecarios#31]
**Configuración RPG MAKER**
Configuración RPG MAKER
**Tareas**
- [x] Instalar RPG MAKER
- [x] Configurar RPG MAKER

**Comment by amelissagomez** [comment]
Instalé y configure RPG MAKER para su uso en mi pc.

**Comment by amauric30** [comment]
esta es la forma para instalar rpg maker versión VM:
https://www.youtube.com/watch?v=ZUTtr_UilW4
