### ISSUE TITLE
Conocer herramienta de desarrollo del juego

### ISSUE THREAD

**Issue by amelissagomez** [ISWPOLI/Servicios_Bibliotecarios#5]
**Conocer RPG MAKER**
Adquirir conocimiento de la aplicación
**Tareas**
- [ ] Lenguaje
- [ ]  Funciones

**Comment by amauric30** [comment]
No he podido subir ningun documento ya que el upload no esta disponible en mi cuenta

**Comment by amauric30** [comment]
ya esta instalado rpg maker
