### ISSUE TITLE
Especificación Nivel 1 Préstamo de Libros

### ISSUE THREAD

**Issue by amelissagomez** [ISWPOLI/Servicios_Bibliotecarios#6]
**Especificación Nivel 1 Préstamo de Libros**
Especificación Nivel 1 Préstamo de Libros
**Tareas**

- [ ] Especificación Personajes del juego
- [ ] Herramientas del juego en el nivel
- [ ] Especificación historia nivel 1 (Préstamo de Libros)

**Comment by amauric30** [comment]
HISTORIA DE PEPITO EL PRIMIPARO Y EL PERDIDO:
Pepito es estudiante del poli y como buen estudiante siempre es responsable, atento, organizado y curioso. Como buen curioso, Pepito busca el mejor lugar que hay para estudiar mientras se encuentra en el poli. Él ha comenzado ha explorar la universidad y se da cuenta que existe el mejor lugar para estudiar, se da cuenta que este lugar se llama biblioteca. Una vez que encuentra este lugar, comienza a preguntarse; como puedo utilizar los computadores, las salas de estudio. Se da cuenta que existen demasiadas cosas, se pregunta: existiendo muchos libros y películas, etc. ¿Cómo puedo acceder a revisarlos y a pedirlos para mirar la información en ellos y demás servicios en la biblioteca?.
Él con cierto grado de duda no sabe por donde empezar, lo primero que hizo fue ir a una sala de estudio, se sentó en una mesa con 4 sillas y cogió un libro de una estantería que decía matemáticas y otro que decía programación de sistemas, los revisó por unos minutos y se interesó mucho en ellos, además porque tenía que hacer algunas tareas de estos temas. Estando allí Pepito, se dió cuenta que existía un código referenciado por letras y números, algunos contenían la referencia por materia y otros eran números seguidos con código de barras. 
Pepito dentro de su espíritu explorador, decidió preguntar al bibliotecario sobre si era posible llevarse estos libros a su casa. 
Fue hasta donde el bibliotecario y le preguntó como podía llevárselos, El bibliotecario al ver la falta de experiencia de Pepito ante los servicios de la biblioteca decidió orientarlo, le dijo:  Pepito tienes que explorar la pagina web de la biblioteca pero yo te puedo decir algunos de los servicios mas generales, estos son:
Pepito para utilizar cualquier de la biblioteca tienes que tener actualizados tus datos en el sistema y tener el carnet de estudiante actualizado también. 

1. Después de esto Pepito, ya puedes entrar a la biblioteca y sentarte en alguna de las mesas disponibles que no requieran préstamos. Pero si quieres ingresar a alguna de las salas para concentrarte mejor tienes que venir aquí y con tu carnet pedir una sala que este disponible por un tiempo limitado.
Esta sala cuenta con varias sillas y puedes estudiar con varios de tus compañeros, pero debes cuidar de esa sala y cuando salgas, dejarla en el mismo estado en el que la encontraste.

2. Pepito, puedes sacar en préstamo libros físicos, pero hay libros de prestamos reservados a algunas horas y no los puedes sacar de la biblioteca:
2.2. préstamo de libros general (domicilio)
2.2.1. etiqueta color
2.3. préstamo de libros con reserva (no domicilio)
2.3.1.etiqueta color
2.4. préstamo de libros virtuales (ínter-bibliotecario)
Para este servicio tienes yo por sistema sisnab de la biblioteca, la biblioteca esta conectada a varias bibliotecas ya sean universidades o bibliotecas públicas. Yo puedo hacer la solicitud de un libro que necesites de esas bibliotecas externas y tu tendrás que ir a retirar el libro que pedimos aquí.

3. Pepito muy entusiasmado siguió poniendo cuidado, el bibliotecario siguió explicando cuando pides en préstamo los libros hay dos maneras de buscarlos Pepito:
3.1. Pepito para ser más ágil la búsqueda del libro que deseas, puedes hacerlo por nombre, referencia o autor a través del sistema de los computadores de la biblioteca, hay encontrarás una base de datos de todos los libros.
3.2. O puedes encontrarlos a través de la estantería y las estanterías están organizadas por materia.

El bibliotecario con el ánimo de enseñar más aun a Pepito le muestra otro servicio que seguro le va
a gustar mucho a Pepito, el bibliotecario le dice:

4. Mira Pepito aquí puedes también mirar algunos filmes de películas en las salas de video, estas salas cuentan con los siguientes elementos:
4.1. Un televisor, el cual debes de cuidar.
4.2. Un reproductor de cds al cual también debes de cuidar.
4.3. La sala cuenta con 4 puestos, el cual puedes entrar con más compañeros de estudio.
4.4. Puedes pedirla para verla en estas salas o puedes pedirla a domicilio.

5. Pepito tienes que tener en cuenta algo muy importante que corresponde a nuestra seguridad al salir de biblioteca:
5.1. Cuantas hayas pedido cualquier material de la biblioteca solo podrás salir con este material una vez sea registrado por el bibliotecario de turno, es decir siempre tienes que venir a esta posición para que yo registre el código de cada material y puedas salir si lo registro como préstamo a domicilio.
