### ISSUE TITLE
Especificación Nivel 2 Préstamo de Películas

### ISSUE THREAD

**Issue by amelissagomez** [ISWPOLI/Servicios_Bibliotecarios#7]
**Especificación Nivel 2 Préstamo de Películas**
Especificación Nivel 2 Préstamo de Películas
**Tareas**

- [ ] Especificación Personajes del juego en el nivel
- [ ] Herramientas del juego en el nivel
- [ ] Especificación historia nivel 2 (Préstamo de Películas)

**Comment by amauric30** [comment]
4. Mira Pepito aquí puedes también mirar algunos filmes de películas en las salas de video, estas salas cuentan con los siguientes elementos:
4.1. Un televisor, el cual debes de cuidar.
4.2. Un reproductor de cds al cual también debes de cuidar.
4.3. La sala cuenta con 4 puestos, el cual puedes entrar con más compañeros de estudio.
4.4. Puedes pedirla para verla en estas salas o puedes pedirla a domicilio.
