### ISSUE TITLE
Creación escenario piso de salones de clase

### ISSUE THREAD

**Issue by cfgonzalezb94** [ISWPOLI/Servicios_Bibliotecarios#79]
**Creación de un escenario en el que se pueda visualizar salones de clases**

**Tareas**

- [ ] Crear escenario en el que se visualice pasillo de salones de clases
- [ ] Crear escenarios de cada uno de los salones de clase
- [ ] Crear personajes que interactuen con estos escenarios

**Comment by amauric30** [comment]
este issue lo puedo trabajar el proximo sprint
