### ISSUE TITLE
Crear escenario biblioteca Virgilio Barco

### ISSUE THREAD

**Issue by amelissagomez** [ISWPOLI/Servicios_Bibliotecarios#86]
**Crear escenario biblioteca Virgilio Barco**
Crear escenario de la biblioteca de un piso 
**Tareas**
- [ ] Crear recepción de la biblioteca
- [ ] Crear estanterías de libros
- [ ] Crear edificio de entrada

**Comment by Lakes1234** [comment]
Diseño vista exterior v
![vistaexterior](https://cloud.githubusercontent.com/assets/25758873/25552284/1d1a39e2-2c5b-11e7-9277-0bb71bf92256.jpg)
0.1
