### ISSUE TITLE
Especificación Nivel 4 Prestamos Interbibliotecarios

### ISSUE THREAD

**Issue by amelissagomez** [ISWPOLI/Servicios_Bibliotecarios#9]
**Especificación Nivel 3 Prestamos Interbibliotecarios**
Especificación Nivel 3 Prestamos Interbibliotecarios
**Tareas**

- [ ] Especificación Personajes del juego en el nivel
- [ ] Herramientas del juego en el nivel
- [ ] Especificación historia nivel 4 (Prestamos Interbibliotecarios)

**Comment by amauric30** [comment]
2.4. préstamo de libros virtuales (ínter-bibliotecario)
Para este servicio tienes yo por sistema sisnab de la biblioteca, la biblioteca esta conectada a varias bibliotecas ya sean universidades o bibliotecas públicas. Yo puedo hacer la solicitud de un libro que necesites de esas bibliotecas externas y tu tendrás que ir a retirar el libro que pedimos aquí.
